import { StyleSheet } from "react-native";
import colors from "../../../styles/colors";

export default StyleSheet.create({
  viewStyle: {
    height: 200,
    flexDirection: "row",
    marginVertical: 12,
    width: "95%",
    alignSelf: "center",
  },
  image: {
    borderRadius: 20,
    flex: 1,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 5,
    shadowColor: "black",
  },
  viewProfile: {
    flexDirection: "row",
    marginHorizontal: 30,
    textAlign: "center",
    alignSelf: "center",
    marginRight: 50,
  },
  profilePic: {
    width: 30,
    height: 30,
    borderRadius: 50,
  },
  name: {
    marginLeft: 10,
    color: "green",
    top: 3,
    fontSize: 20,
    fontWeight: "200",
  },
  viewThree: {
    flex: 1,
    width: "90%",
    alignSelf: "center",
    borderRadius: 25,
    backgroundColor: colors.background,
    paddingBottom: 20,
    marginTop: 5,
  },
  title: {
    marginTop: 15,
    marginBottom: 15,
    color: "green",
    fontSize: 19,
    textAlign: "center",
    alignSelf: "center",
    fontWeight: "300",
    textTransform: "uppercase",
  },
  text: {
    textTransform: "uppercase",
    color: "green",
    fontSize: 16,
    marginTop: 15,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    fontWeight: "300",
  },
  textTwo: {
    color: "black",
    fontSize: 13,
    marginBottom: 5,
    textAlign: "justify",
    marginLeft: 10,
    marginRight: 10,
    fontWeight: "300",
  },
  favButton: {
    width: 43,
    height: 43,
    backgroundColor: "white",
    borderRadius: 50,
    position: "absolute",
    right: 30,
    top: 140,
  },
  gradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  favIcon: {
    alignSelf: "center",
    top: 11,
    fontSize: 25,
  },
});
